name: 'Nodeapp'

on:
  workflow_dispatch:
  pull_request:

jobs:
  build-node-app:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: npm

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Prettier
        run: |
              npm install --save-dev --save-exact prettier        
              npm run prettier

      - name: testing
        run: CI=true npm run test

      - name: Build
        run: npm run build